export const FLOOR_LIST_REQUEST = 'FLOOR_LIST_REQUEST'
export const FLOOR_LIST_SUCCESS = 'FLOOR_LIST_SUCCESS'
export const FLOOR_LIST_FAIL = 'FLOOR_LIST_FAIL'

export const FLOOR_DETAILS_REQUEST = 'FLOOR_DETAILS_REQUEST'
export const FLOOR_DETAILS_SUCCESS = 'FLOOR_DETAILS_SUCCESS'
export const FLOOR_DETAILS_FAIL = 'FLOOR_DETAILS_FAIL'